version: '3.9'

services:
  database:
    image: mariadb:10.5.8
    container_name: assignment_db
    environment:
      - MYSQL_DATABASE=mr_db
      - MYSQL_USER=mr_user
      - MYSQL_PASSWORD=mr_password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./assignment-be/data/db:/var/lib/mariadb
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - assignment_network

  server:
    container_name: assignment_backend_service
    env_file:
      "./assignment-be/.env"
    build:
      context: ./assignment-be
      dockerfile: Dockerfile
    image: "assignment/backend"
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - assignment_network

  assignment-fe:
    container_name: assignment_fe_service
    build:
      context: ./assignment-fe
      dockerfile: ./Dockerfile
    image: "assignment/frontend"
    networks:
      - assignment_network
    ports:
      - "8081:8081"

networks:
  assignment_network: